-- generated by scripts/seed-posts.mjs from apps/static/src/content/blog/*.md
BEGIN TRANSACTION;
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('aci-medhabi-carnival', 'ACI Medhabi Carnival: A Day of Learning and Celebration', 'Primary students joined a full day of chess against a Grandmaster, art stations, tangram puzzles, book reading, robotics demos, and telescope activities at the ACI Centre in Tejgaon.', 'Event', 'Samin Yasar Ahmed', '/images/aci-medhabi-carnival.webp', 'Last Sunday, the ACI Centre in Tejgaon transformed into a vibrant hub of curiosity for primary school students across Dhaka. The ACI Medhabi Carnival brought together young learners for a day packed with interactive challenges, creative activities, and a once-in-a-lifetime face-off against a chess Grandmaster.

## Chess Against a Grandmaster

The day''s headline moment was a simultaneous chess exhibition where students had the opportunity to play against a titled Grandmaster. Students who had never touched a chess board sat across the board with as much focus as seasoned players. For many, it was a lesson in thinking many moves ahead - a skill that translates directly into mathematics and science problem-solving.

## What Else Was on Offer

The carnival floor was packed with stations designed to spark curiosity:

- **Art stations** - students explored geometric patterns and symmetry through drawing and colouring
- **Tangram puzzles** - spatial reasoning challenges that had participants fully absorbed
- **Book reading corner** - a quiet zone stocked with age-appropriate science and math books, with volunteers on hand to guide reading
- **Robotics demos** - BdMSO volunteers showcased basic robotics kits and let students try building simple circuits
- **Telescopes** - a personal favourite: students queued to get a magnified look at the sky and nearby structures, sparking questions about optics and space science

## Why Events Like This Matter

BdMSO exists not just to select a national team, but to build a culture of curiosity at the primary level. Events like the ACI Medhabi Carnival show students that mathematics and science are not confined to textbooks - they are alive in games, puzzles, machines, and the sky above.

A huge thank you to ACI and everyone who made the event possible. We look forward to bringing more students into these experiences ahead of BdMSO 2026.', 1, 0, '2026-04-29', datetime('now'), NULL);
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('bdmso-2025-national-round-prothom-alo', 'BdMSO 2025: National Round Concludes at St. Joseph', 'Over 200 primary students competed in the inaugural Bangladesh Mathematics and Science Olympiad''s national round at St. Joseph Higher Secondary School in Dhaka. Fifty-two students earned medals, and the top six in each subject will represent Bangladesh at IMSO 2025 in Kedah, Malaysia.', 'Press', 'Prothom Alo English Desk', '/images/press/prothomalo-saint-joseph.webp', '*This post is a summary of [press coverage published by Prothom Alo](https://en.prothomalo.com/youth/education/5w0flop9aq) on 22 August 2025.*

Bangladesh held its inaugural Mathematics and Science Olympiad (BdMSO) for primary-level students on 22 August 2025, aiming to foster curiosity and build strong foundational knowledge in mathematics and science. The national round was hosted at **St. Joseph Higher Secondary School** in Dhaka and drew over 200 participants from across the country - more than 150 students in mathematics and more than 100 in science.

After the written exams, organizers entertained participants with robotics and drone exhibitions and a magic show.

## Distinguished Guests

The day''s distinguished attendees included:

- **Brother Leo James Pereira** - Principal, St. Joseph Higher Secondary School
- **Sarwat Reza** - Cambridge University Press and Assessment, Country Lead
- **Jahangir Masud** - Principal, Legend International School
- **Professor Farzana Alam** - European University of Bangladesh
- **Jannatul Ferdous Sigma** - Pearson Bangladesh, Regional Development Manager

Brother Leo encouraged the participants: *"This experience will be invaluable on your journey to fulfilling your dreams."*

Sarwat Reza affirmed that *"competitions like this play a vital role in nurturing students'' knowledge and skills."*

## Results

Fifty-two students were awarded medals across both subjects:

- **Mathematics:** 4 gold, 9 silver, 13 bronze
- **Science:** 5 gold, 9 silver, 12 bronze

### Champions

- **Mathematics:** Md Nabeeh Hossain (Grade 5, St. Joseph Higher Secondary School)
- **Science:** Syed Ayaan Isa (Grade 4, Lighthouse International School)

## Next Steps

Six mathematics and six science winners will represent Bangladesh at the **22nd International Mathematics and Science Olympiad (IMSO)**, scheduled for **4-10 October 2025 in Kedah, Malaysia**, with nearly 300 students from 23 countries participating.

## Organizers and Partners

BdMSO 2025 was organized by the **Bangladesh Open Source Network (BdOSN)** and the **Society for the Popularization of Science, Bangladesh (SPSB)**, supported by **MassLab**, **Tems Academy**, and **Reflective Teen**.

---

*Source: Prothom Alo English - ["Bangladesh Mathematics and Science Olympiad 2025: National round concludes"](https://en.prothomalo.com/youth/education/5w0flop9aq).*', 1, 0, '2025-08-22', datetime('now'), NULL);
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('bdmso-2026-team-orientation', 'BdMSO 2026: Team Orientation Launch', 'Mentors and volunteers gathered for a four-hour orientation to prepare BdMSO 2026 - Bangladesh''s national math and science olympiad pathway for primary students bound for IMSO in Indonesia.', 'Announcement', 'Samin Yasar Ahmed', '/images/team/team-orientation.webp', 'After months of planning, BdMSO 2026 officially kicked off with a four-hour team orientation held at the BdMSO and SPSB Office Classroom. Mentors, volunteers, and coordinators came together to align on the vision, responsibilities, and timeline for Bangladesh''s most important primary-level science and mathematics olympiad.

## What Is BdMSO?

BdMSO - the Bangladesh Mathematics and Science Olympiad - is Bangladesh''s only national olympiad for primary school students, selecting the top 12 students (6 in Math, 6 in Science) to represent the country at **IMSO 2026** in Indonesia. The competition is open to students under 13 enrolled in Grade 6 or lower.

## Inside the Orientation

The session covered everything the team needs to run a smooth cycle:

- **Program overview** - the full 2026 calendar from registration through to international delegation
- **Role assignments** - mentors took on subject areas (Mathematics and Science), while volunteers split into logistics, outreach, and media
- **Curriculum alignment** - the team reviewed the official BdMSO syllabus to ensure training content matches the national round and TST format
- **Community goals** - beyond competition, the team discussed how to grow participation from schools across Bangladesh, including those outside Dhaka

## The Road Ahead

With orientation complete, the team moves into the active preparation phase. Registration for the National Olympiad opens in May 2026. In the meantime, mentors will begin structured preparation sessions for returning students.

If your child is in Class 3–6 and interested in mathematics or science, [register early](/registration) and start preparing with the official BdMSO syllabus.', 1, 0, '2026-05-01', datetime('now'), NULL);
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('lab-day-primary-kids', 'Lab Day for Primary Kids: A Day of Hands-On Discovery', 'Twelve students spent a full day mapping skeletal structures, exploring light and prisms, using microscopes, and creating Elephant Toothpaste while learning about chemical reactions.', 'Workshop', 'Samin Yasar Ahmed', '/images/lab-day-primary.webp', 'Twelve primary school students spent a full day doing real science. Not reading about it, not watching videos - actually doing it. The BdMSO Lab Day brought together a small group and gave them access to equipment and experiments that most primary students in Bangladesh never get to experience.

## The Experiments

**Skeletal Mapping**

Students were given printed diagrams and physical models to map the major bones of the human skeleton. The exercise connected biology theory to something tangible, and the conversations about how different bones protect different organs were some of the most engaged moments of the day.

**Light and Prisms**

Using prisms and a focused light source, students split white light into its component colours and observed how different materials bend light differently. Several students immediately connected this to rainbows - which led to a ten-minute discussion about why the sky is blue.

**Microscopes**

Students prepared slides and looked at onion skin cells, pond water, and their own hair under microscopes. Seeing cells for the first time - actual cells, not diagrams - was a turning point for many. One student kept asking to look at different things around the room under the lens.

**Elephant Toothpaste**

The day''s showstopper: a chemical reaction between hydrogen peroxide and yeast that produces a rapid, dramatic foam. Students predicted what would happen before the reaction, observed it happening, then discussed why - decomposition, catalysts, and exothermic reactions.

## Why It Matters

The IMSO Science paper includes an experimental component. Students who have never held lab equipment are at a significant disadvantage when faced with a timed experiment. Lab Day is BdMSO''s way of closing that gap - giving students exposure to the process of science, not just the content.

More Lab Days are planned ahead of BdMSO 2026. Keep an eye on the [programs page](/programs) for dates.', 1, 0, '2026-05-01', datetime('now'), NULL);
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('maryam-mirzakhani-school-2026', 'Maryam Mirzakhani School of Mathematics and Science', 'A 3-day foundational program for primary students (Grade 5 and below), inspired by the playful, visual problem-solving of Maryam Mirzakhani - the first woman to win the Fields Medal. 23–25 May 2026 at MASLab, Dhanmondi.', 'Program', 'BdMSO Team', '/images/maryam-mirzakhani-school.webp', 'When we think of advanced mathematics and science, we often picture rigid rules and dry memorization. But for Maryam Mirzakhani, the first woman to win the Fields Medal - the highest honor in mathematics - it was an entirely different world.

As a child, Maryam didn''t dream of numbers; she wanted to be a writer. When she eventually discovered mathematics, she realized it wasn''t an abstract chore - it was a beautiful form of storytelling. Maryam was famous for her incredibly playful and visual approach to problem-solving. She would spread giant sheets of white paper across the floor, drawing elaborate doodles, shapes, and diagrams to find hidden patterns. She beautifully described tackling a tough problem as *"being lost in a jungle and trying to use all the knowledge you can gather to come up with new tricks."*

This is exactly why we are hosting the **Maryam Mirzakhani School of Mathematics and Science** for primary students (Grade 5 and below).

We want to show early-age learners that STEM is a canvas for imagination. Inspired by Maryam''s visual, creative mindset, this 3-day foundational intervention moves away from rote learning. Instead, it builds deep conceptual understanding, sharpens analytical thinking, and instills a lifelong passion for discovery. Give your child an early, competitive edge to unlock their full potential and prepare them for the exciting academic journey ahead.

---

## At a glance

- **Dates:** 23, 24, 25 May 2026
- **Venue:** MASLab, Dhanmondi, Dhaka
- **Subjects:** Mathematics / Science / Both
- **Who it''s for:** Primary students, Grade 5 and below
- **Cohort:** Cohort 1

---

## Register and full schedule

**Register here:** [festive.rocks/e/prepbdmso](https://festive.rocks/e/prepbdmso)

For the complete 3-day class routine, session timings, and fee details for each subject track, see the [full program page](/programs/maryam-mirzakhani-school).

You can also follow the [Facebook event](https://www.facebook.com/share/18RoSRT7WG/) for updates.', 1, 0, '2026-05-17', datetime('now'), NULL);
INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) VALUES ('stem-foundation-course', 'STEM Foundation Course: Batch One Completed', 'The online foundation program for classes 3–6 ran from March 14 to May 1, covering scientific method, chemistry, physics, mathematics, coding, astronomy, environmental science, biology, and machine learning over 20 sessions.', 'Program', 'Samin Yasar Ahmed', '/images/stem.webp', 'From March 14 to May 1, ten primary school students took part in BdMSO''s first STEM Foundation Course - a 20-session online program designed to build strong conceptual foundations before the national round.

The course was built around one core idea: great problem-solvers are not made through memorisation. They are made through genuine understanding, and genuine understanding comes from seeing how ideas connect.

## What the Course Covered

Over seven weeks, the curriculum moved through nine subject areas:

1. **Scientific Method** - observation, hypothesis, experimentation, and interpretation. Students designed and ran simple experiments at home.
2. **Chemistry** - matter, mixtures, reactions, and everyday chemistry (why bread rises, why iron rusts).
3. **Physics** - forces, motion, light, and sound, grounded in examples from everyday life.
4. **Mathematics** - number theory, geometry, pattern recognition, and competition-style problem solving.
5. **Coding** - introductory logic and algorithmic thinking using block-based coding.
6. **Astronomy** - the solar system, Earth''s position in space, and basic observational astronomy.
7. **Environmental Science** - ecosystems, human impact, climate, and conservation.
8. **Biology** - cells, the human body, plant science, and basic genetics.
9. **Machine Learning** - a simplified introduction to how computers learn from data, with age-appropriate analogies.

## The Lab Day

The course wrapped up with an in-person Lab Day - a full hands-on session where students put theory into practice. They ran experiments they had only seen online, used equipment for the first time, and worked through problems together.

The transition from screen to lab was telling. Students who had been quiet during online sessions lit up when they could touch and observe things directly. The Lab Day became the clearest evidence that hands-on experience cannot be replaced.

## What''s Next

Students who completed the STEM Foundation Course will be given priority access to the BdMSO Preparatory Course ahead of the 2026 national round. For new students, the next cohort will be announced on the [programs page](/programs).', 1, 0, '2026-04-28', datetime('now'), NULL);
COMMIT;
