// Seed the D1 `posts` table from the existing blog markdown
// (apps/static/src/content/blog/*.md) so the admin Posts screen lists them.
// Emits SQL on stdout. Re-runnable (INSERT OR REPLACE).
//
//   node scripts/seed-posts.mjs > db/seeds/posts.sql
//   wrangler d1 execute bdmso --local  --file=db/seeds/posts.sql
//   wrangler d1 execute bdmso --remote --file=db/seeds/posts.sql   (when ready)

import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "apps/static/src/content/blog");

const q = (v) => (v == null || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const b = (v) => (v ? 1 : 0);

function parse(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: raw.trim() };
  const fm = {};
  for (const line of m[1].split("\n")) {
    const mm = line.match(/^([A-Za-z_]+):\s*(.*)$/);
    if (!mm) continue;
    let val = mm[2].trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    fm[mm[1]] = val;
  }
  return { fm, body: m[2].trim() };
}

// posts.image is "R2 key or /images/ path"; blog frontmatter uses "images/x.webp".
function normImage(img) {
  if (!img) return null;
  if (img.startsWith("http") || img.startsWith("/")) return img;
  return "/" + img;
}

const files = readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
console.log("-- generated by scripts/seed-posts.mjs from apps/static/src/content/blog/*.md");
console.log("BEGIN TRANSACTION;");
for (const f of files) {
  const { fm, body } = parse(readFileSync(join(dir, f), "utf8"));
  const slug = fm.slug || f.replace(/\.md$/, "");
  const featured = fm.featured === "true" || fm.featured === true;
  console.log(
    "INSERT OR REPLACE INTO posts (slug, title, excerpt, category, author, image, body_md, published, featured, published_at, updated_at, updated_by) " +
    `VALUES (${q(slug)}, ${q(fm.title)}, ${q(fm.excerpt)}, ${q(fm.category)}, ${q(fm.author)}, ${q(normImage(fm.image))}, ${q(body)}, 1, ${b(featured)}, ${q(fm.date)}, datetime('now'), NULL);`
  );
}
console.log("COMMIT;");
